# Generated by Django 6.0.3 on 2026-05-29 09:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField(unique=True)),
                ('state_code', models.IntegerField(db_index=True, null=True)),
                ('dcode', models.IntegerField(db_index=True, null=True)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('gapa_napa', models.CharField(db_index=True, max_length=100)),
                ('type_gn', models.CharField(max_length=50)),
                ('gn_code', models.FloatField(null=True)),
                ('ward_number', models.IntegerField(db_index=True, null=True)),
                ('ddgnww', models.FloatField(null=True)),
                ('ddgn', models.IntegerField(null=True)),
                ('center', models.CharField(blank=True, max_length=100, null=True)),
                ('area_sqkm', models.FloatField(null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'indexes': [models.Index(fields=['state_code', 'district', 'gapa_napa', 'ward_number'], name='core_ward_state_c_01179f_idx')],
            },
        ),
    ]
